# Generated by Django 5.1.4 on 2025-01-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Book',
            fields=[
                ('bookname', models.CharField(max_length=50)),
                ('authorname', models.CharField(max_length=50)),
                ('isbn', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('bookdoc', models.ImageField(upload_to='Book_Image/')),
                ('Review', models.CharField(max_length=30)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.catagory')),
            ],
        ),
    ]
