# Generated by Django 5.1.4 on 2025-01-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_alter_add_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_book',
            name='Review',
        ),
        migrations.AddField(
            model_name='add_book',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
