# Generated by Django 5.1.4 on 2025-01-07 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publisher_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pemail', models.CharField(max_length=50)),
                ('pmobileno', models.CharField(max_length=50)),
                ('ppassword', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pdoc', models.FileField(upload_to='document/')),
                ('paddress', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
