# Generated by Django 5.1.4 on 2025-01-13 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cus_register',
            fields=[
                ('cname', models.CharField(max_length=50)),
                ('ccontact', models.CharField(max_length=50)),
                ('cemail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cpwd', models.CharField(max_length=30)),
                ('cdob', models.CharField(max_length=30)),
                ('caddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pub_register',
            fields=[
                ('pname', models.CharField(max_length=50)),
                ('pemail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pmobileno', models.CharField(max_length=50)),
                ('ppassword', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pdoc', models.FileField(upload_to='document/')),
                ('paddress', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='publisher_register',
        ),
    ]
