# Generated by Django 5.1.4 on 2025-01-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_cus_register_pub_register_delete_publisher_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub_register',
            old_name='ppassword',
            new_name='ppwd',
        ),
    ]
