# Generated by Django 5.1.4 on 2025-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(max_length=50)),
                ('cocontact', models.CharField(max_length=50)),
                ('coemail', models.CharField(max_length=50)),
                ('coaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
